apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: public-internetgateway
spec:
  forProvider:
    region: us-east-1
    vpcIdRef:
      name: main-vpc
  providerConfigRef:
    name: default